---
title: "drosera: A Botanical Alternative to the iris Dataset"
author: Roman M. Link
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description
`drosera` is a data package that provides a botanical replacement dataset for Anderson and Fisher's famous `iris` dataset that is free from its troublesome past. It is based on a set of plants that I am growing on my windowsill which I measured with a caliper in a matter of a couple of hours to have an example dataset for the [`corrmorant`](https://github.com/r-link/corrmorant) package and is entirely devoid of scientific rigor. However, I believe it is a useful example dataset that will hopefully enable some people to replace `iris` in their code and package documentation, and maybe even spark an interest in carnivorous plants in a couple of R users.

It is published under a [Creative Commons Zero license](https://github.com/r-link/drosera/blob/master/LICENSE), so it is free to use in any kind of commercial or non-commercial setting. In particular, if you need a replacement dataset for `iris` for the examples in your R package, feel free to add `drosera` to the package without any additional precautions.

However, it would be kind if you add a link to the package's [Github page](https://github.com/r-link/drosera) in case you decide to use it (and maybe drop me a line so I can link your project in the repository), but I won’t be mad if you don’t.
